Document: gdis-prolog
Title: Debian gdis-prolog Manual
Author: <insert document author here>
Abstract: This manual describes what gdis-prolog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gdis-prolog/gdis-prolog.sgml.gz

Format: postscript
Files: /usr/share/doc/gdis-prolog/gdis-prolog.ps.gz

Format: text
Files: /usr/share/doc/gdis-prolog/gdis-prolog.text.gz

Format: HTML
Index: /usr/share/doc/gdis-prolog/html/index.html
Files: /usr/share/doc/gdis-prolog/html/*.html
